exports.ARTICLE = "/article"
exports.BLOG = "/Blog"
exports.HOME = "/"
exports.TEAMS = "/team"
exports.PROJECTS = "/projects"
exports.WORK_WITH_US = "/WorkWithUsPage"
exports.CONTACT = "/Contact"
exports.ABOUT = "/About"
